### ISSUE TITLE
Create file and folder problems on Linux

### ISSUE THREAD

**Issue by ambarket** [ambarket/botbattle#1]
Permissions Issue:
Create Folder -> /test -> ERRACC (This is what should happen since app doesn't have access to root)
Create File -> /test/test2.txt -> Infinite loop (Error creating directory: Error: ENOENT, mkdir '')
--- This may actually just be a side effect of the backslash issue described below since the same look occurs when trying to make createFile automatically create directories

Create Folder:
test2/test3 -> works as expected
test2\test3 -> Creates folder literally named "test2\test3" (Linux doesn't support backslash in file and folder paths as windows does. And windows supports forward slash so make everything forward slash and if the user enters backslashes should probably automatically convert them to forward slashes for consitency)

Create File:
\test\test2.txt -> Again literally creates the file "\test\test2.txt " inside the application directory

test2/test2.txt -> Works as expected creates test2.txt inside test2 folder (test2 folder already existed)
test/test2.txt -> Infinite loop (Error creating directory: Error: ENOENT, mkdir '')  (test folder didn't exist)
---- So the automatic folder creation by createFile doesn't work if test folder didnt exist

In general - Main problem seems to be the backslash, forward slash mismatch.

**Comment by Stevenpc3** [comment]
Should I try to support both windows and linux by checking the operating system (which is possible in node) or just for linux?

**Comment by ambarket** [comment]
I think we should just worry about linux for now as other aspects of the system may be harder to make work for both. We have enough work as it is.

**Comment by Stevenpc3** [comment]
Fair enough. It would be easy to add, but it could cause cascading errors later, so I agree.  We should all run linux os or vm.  Is "akira" running linux?

**Comment by Stevenpc3** [comment]
Made a minor change need to know if it helped on linux machines.

**Comment by Stevenpc3** [comment]
This seems fixed now.
