### ISSUE TITLE
GameManager moved and rearranged

### ISSUE THREAD

**Issue by ambarket** [ambarket/botbattle#11]
I have moved around the GameManager source files to a format that works well on our end. However I'm not sure if it works for your development environment Randall. The main idea was to separate test source files form the regular ones. This is necessary because we compile all the files in the folder and Junit has dependencies that cause compilation on command line to fail. Also removed packages to keep command line compilation simple. I believe everything should still work the same and eclipse will compile all files in all sub directories of /src/ and they are all in the default package so test classes should have package level access to all other classes. 

Also moved the bots to their own folder, this isn't a requirement just looks a bit nicer. I assume that will require changes to any hard coded stuff you have for testing though. 

At your convenience please verify that you're able to develop with the new set up, and if you can't make the changes you need to so we can come to common ground before anybody develops more GameManager code and so that we can delete the TestBotAndJudge folder. 

Overall goal is to smooth the development and integration of the GameManger with BotBattleApp and not require making copies of the files around as we have been this week.

**Comment by Akiira** [comment]
The file structure on my branch is now very similar to how you moved them around, and eclipse is fine with working with this structure. Can you give it a look and tell me if you guys can work with it.

**Comment by ambarket** [comment]
I made necessary changes to our code and committed it. Copied GameManager2 into GameManager and also removed Game.java from production and put it in Games folder. THis isn't required if you really need it in there but from our perspective upon initial configuration we make a copy of the Production folder, add the Game.java file uploaded through the webform, then compile so if its there already it will be overridden. Feel free to merge this branch back into master after you delete the GameManager2 folder.
