### ISSUE TITLE
Test Arena connection management and tracking discussion

### ISSUE THREAD

**Issue by Stevenpc3** [ambarket/botbattle#5]
From ambarket:

Cookies and sessions don't seem to be a good answer. Mainly because if you open a bunch of browser tabs they will all use the same cookie and session but will not all send and receive the same ajax requests. Therefore maintaining valid state across multiple browser tabs will be a nightmare.

Imagine there is a running game, with two tabs connected to that session. And the user submits moves via both of them. The client JavaScript only receives the game states requested in that tab so the client JavaScript would get all out of whack and enter invalid states.

Even trying to lock it down to only only tab per browser is not an easy task and requires you to maintain your own id's for each open tab and ensure that there aren't more than one of your issued id's trying to use the same session.

And at least from what I read we can't use Mongo for storing test arena instances as we originally planned because we cant store the game manager spawned process in it. Mongo does not preserve the original objects but converts them to its own representation. So for example attempting to later grab that process object to kill the spawned process would not work, and this is something we absolutely have to be able to do.

What I'm thinking is that we use something very close to what is already implemented in SocketIOConectionTracker, just without socket.io and with our own generated ids instead. There are a number of modules that we can use to generate secure ids. And we create our own simple data structure to store test arena sessions kind of like we did in MultiClientPrototype but a bit more elaborate. However I'm thinking maybe further work on this should wait until after we figure out how to authenticate logged in users and maintain their logged in sessions, just in case research into that sheds more light into how we can make cookies and sessions work for this case.

**Comment by Stevenpc3** [comment]
I wanted to move this out of the wiki

Also,  we seem to have solved this problem.

**Comment by ambarket** [comment]
This is solved/not relevant, marking as resolved
